import * as Crypto from 'expo-crypto'

import type { ClinicalFinding } from '../../models/ClinicalFinding'
import type { ClinicalRule } from '../ClinicalRule'
import type { ClinicalRuleContext } from '../ClinicalRuleContext'

export interface ClinicalClassificationRuleInput {}

 /**
  * Converts a clinical guide classification
  * into a clinical finding.
  *
  * Classification is generated by ClinicalEngine.
  */

export class ClinicalClassificationRule
  implements ClinicalRule<ClinicalClassificationRuleInput>
{
  evaluate(
    _input: ClinicalClassificationRuleInput,
    context: ClinicalRuleContext,
  ): ClinicalFinding[] {
    const result = context.clinicalResult

    if (!result) {
      return []
    }

    return [
      {
        id: Crypto.randomUUID(),

        type: 'blood-pressure-classification',

        title:
          `Clasificación de presión arterial: ${result.classification}`,

        description:
          `Clasificación generada por la guía ${result.guideline}.`,

        severity: 'moderate',

        guidelineId:
          context.guideline?.id,

        createdAt:
          new Date().toISOString(),
      },
    ]
  }
}
