import type { StatisticsSummary } from '../../statistics/models/StatisticsSummary'
import type { ClinicalFinding } from './ClinicalFinding'
import type { ClinicalGuideline } from './ClinicalGuideline'

/**
 * Represents the result of a clinical interpretation process.
 *
 * ClinicalAnalysis connects measurements, statistical summaries,
 * patient context and clinical knowledge.
 *
 * It does not calculate statistics or replace raw measurements.
 */

export interface ClinicalAnalysis {
  // Identity

  id: string

  patientId: string

  createdAt: string

  // Clinical knowledge used

  guideline?: ClinicalGuideline

  // Statistical information used for interpretation

  statistics?: StatisticsSummary

  // Clinical findings generated by analysis

  findings: ClinicalFinding[]

  // General interpretation

  summary?: string

  // Extensibility

  metadata?: Record<string, unknown>
}
