import type { ClinicalFinding } from './ClinicalFinding'
import type { ClinicalGuideline } from './ClinicalGuideline'

/**
 * Represents the result of a clinical interpretation process.
 *
 * ClinicalAnalysis connects measurements, patient context
 * and clinical knowledge.
 *
 * It does not calculate statistics or replace raw measurements.
 */

export interface ClinicalAnalysis {
  // Identity

  id: string

  patientId: string

  createdAt: string

  // Guideline used for interpretation

  guideline?: ClinicalGuideline

  // Clinical findings generated by analysis

  findings: ClinicalFinding[]

  // General interpretation status

  summary?: string

  // Extensibility

  metadata?: Record<string, unknown>
}
